/**
 * Country -> currency code, and static approximate EGP value of 1 unit of
 * each currency. These are indicative rates for display only — actual
 * Cash on Delivery payment is always collected in EGP. Rates should be
 * refreshed periodically; they are not fetched live.
 */
export const COUNTRY_CURRENCY: Record<string, string> = {
  Egypt: "EGP",
  Algeria: "DZD",
  Argentina: "ARS",
  Australia: "AUD",
  Austria: "EUR",
  Bahrain: "BHD",
  Bangladesh: "BDT",
  Belgium: "EUR",
  Brazil: "BRL",
  Canada: "CAD",
  China: "CNY",
  Colombia: "COP",
  Cyprus: "EUR",
  Czechia: "CZK",
  Denmark: "DKK",
  Ethiopia: "ETB",
  Finland: "EUR",
  France: "EUR",
  Germany: "EUR",
  Greece: "EUR",
  India: "INR",
  Indonesia: "IDR",
  Iraq: "IQD",
  Ireland: "EUR",
  Italy: "EUR",
  Japan: "JPY",
  Jordan: "JOD",
  Kenya: "KES",
  Kuwait: "KWD",
  Lebanon: "LBP",
  Libya: "LYD",
  Malaysia: "MYR",
  Malta: "EUR",
  Mexico: "MXN",
  Morocco: "MAD",
  Netherlands: "EUR",
  "New Zealand": "NZD",
  Nigeria: "NGN",
  Norway: "NOK",
  Oman: "OMR",
  Pakistan: "PKR",
  Philippines: "PHP",
  Poland: "PLN",
  Portugal: "EUR",
  Qatar: "QAR",
  Romania: "RON",
  "Saudi Arabia": "SAR",
  Singapore: "SGD",
  "South Africa": "ZAR",
  "South Korea": "KRW",
  Spain: "EUR",
  Sudan: "SDG",
  Sweden: "SEK",
  Switzerland: "CHF",
  Syria: "SYP",
  Thailand: "THB",
  Tunisia: "TND",
  Turkey: "TRY",
  Ukraine: "UAH",
  "United Arab Emirates": "AED",
  "United Kingdom": "GBP",
  "United States": "USD",
  Yemen: "YER",
};

/** Approximate EGP value of 1 unit of the given currency. */
export const EGP_PER_UNIT: Record<string, number> = {
  USD: 49,
  EUR: 53,
  GBP: 62,
  AED: 13.3,
  SAR: 13.1,
  QAR: 13.5,
  KWD: 160,
  BHD: 130,
  OMR: 127,
  JOD: 69,
  CAD: 36,
  AUD: 32,
  NZD: 30,
  CHF: 56,
  SEK: 4.6,
  NOK: 4.5,
  DKK: 7.1,
  PLN: 12.3,
  CZK: 2.1,
  RON: 10.6,
  TRY: 1.4,
  CNY: 6.8,
  JPY: 0.33,
  INR: 0.59,
  PKR: 0.18,
  BDT: 0.41,
  IDR: 0.0031,
  MYR: 10.6,
  SGD: 36,
  PHP: 0.86,
  THB: 1.4,
  KRW: 0.036,
  ZAR: 2.7,
  NGN: 0.032,
  KES: 0.38,
  ETB: 0.42,
  MAD: 4.9,
  TND: 15.6,
  DZD: 0.37,
  LYD: 10.1,
  IQD: 0.037,
  LBP: 0.00055,
  SYP: 0.0038,
  YER: 0.196,
  SDG: 0.082,
  BRL: 8.9,
  ARS: 0.052,
  MXN: 2.6,
  COP: 0.0117,
  UAH: 1.19,
};

export function currencyForCountry(country: string): string | null {
  return COUNTRY_CURRENCY[country] ?? null;
}

/** Converts an EGP amount into the given currency, or null if unsupported. */
export function convertFromEGP(egpAmount: number, currencyCode: string): number | null {
  if (currencyCode === "EGP") return egpAmount;
  const rate = EGP_PER_UNIT[currencyCode];
  if (!rate) return null;
  return egpAmount / rate;
}
