// Real customer testimonials for the guided journals, shown verbatim on
// /shop — user-generated content, so (like journal entries and resource
// article bodies elsewhere in this app) intentionally left untranslated
// regardless of site locale.
export const SHOP_TESTIMONIALS: string[] = [
  "It’s my favorite part of the day! I’ve never started my day with a moment of self-reflection before and I feel that it gives me a small boost to continue my day and do all my tasks in a more mindful and loving way because I kind of have in mind what I just expressed while journaling just before. It’s amazing thank you!",
  "Self-care wasn’t a big deal to me until I knew about letitout by k.\nI really didn’t know that it’s necessary to know more about myself, my fears, my thoughts, and my boundaries….\nSometimes I feel so tired, physically, and anxious and I didn’t know that the reason behind this could be lack of sleep or lack of self-care. I really need to take some breaks not just to sleep but a break in general, to have my energy back.\nAnd I became more aware about this idea since I followed letitout account because there was a post about mental exhaustion and I found out that this is meeee in a really horrible way.\nI decided to focus on my inner peace and my mental health.\nSooo Everyday I give myself 5 minutes with my letitout journal, to discover me, and to heal me.",
  "The journal is amazing! It’s very soothing and therapeutic to get to talk to yourself and your thoughts by jottings down everything on paper in a very smooth manner. I love it! I really recommend everyone to purchase both journals by Let It Out and foster some self-love and self-care 🧚🏻🧚🏻",
  "This journal is honestly god sent. I was never really the type to believe in mental issues to the point where I didn’t think they existed. But the way this journal is laid out made me feel like it wasn’t some type of homework, but more of an escape. I’m not the type to talk about my emotions to anyone, no matter how dear and close, In fear of hurting them or driving them away, so this journal did its job and more into making me cope with my issues in a more healthy way.\nI wish I had this journal when i was younger, definitely would’ve helped make me a less messed up person than I am today. But it’s never too late to discover new things about yourself and grow.\nBuying this journal was one of the best decisions I’ve ever made.",
  "Yes it definitely helped me a lot. I'm not usually the type of person that opens up to people and journaling was never a thing for me but i thought i'd give it a chance and it made me more self conscious and i discovered a lot of things about myself that i never thought about through these creative questions. I know my worth now and i am for sure working on loving myself more :)",
  "Ive never done sth like this before it helped me explore my emotions and where do i stand with them",
  "The journal has helped me dicover myslef from a different perspective and see myself from a different angle\nand definitely made me feel so much better about myself",
  "I realized that when i journal alone I write things that I’m already aware of while Let it out is helping me think deeper and not just let out what’s on the surface, it’s asking me questions that I wouldn’t usually ask myself which is helping me realize things I wasn’t aware of.",
  "It’s really helping. I like journaling in general and was skeptical about what let it out will add to my journaling if its already a habit",
];
