// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7 removed `directUrl` from schema.prisma entirely — the CLI
    // (migrate/generate/studio) now takes its own connection here, separate
    // from the pooled connection the running app uses via the driver
    // adapter in src/lib/db.ts. Migrations need a direct (unpooled)
    // connection to run their DDL/advisory-lock operations reliably, so
    // this prefers DIRECT_URL and only falls back to DATABASE_URL where a
    // separate direct connection isn't configured (e.g. local dev).
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
