// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Prisma 7 removed `directUrl` from the schema's datasource block —
    // connection URLs live here instead. This is the CLI/migration
    // connection, so point it at DIRECT_URL when one is set (an unpooled
    // link for providers that front Postgres with a pooler, which cannot
    // run migrations). Runtime queries keep using DATABASE_URL through the
    // driver adapter in src/lib/db.ts.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
