ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "cbtExerciseHidden" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "SiteSettings" ADD COLUMN IF NOT EXISTS "hiddenArticleSlugs" TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[];
