-- Optional Arabic translations for journal prompts, matching the same
-- nullable/fallback pattern used elsewhere (Article/Product/Counselor).
-- Seed data alone never reaches production, so this has to happen here
-- (see CLAUDE.md).
ALTER TABLE "JournalPrompt" ADD COLUMN "textAr" TEXT;
ALTER TABLE "JournalPrompt" ADD COLUMN "categoryAr" TEXT;

UPDATE "JournalPrompt" SET "textAr" = 'في إحساس إنت باعد عنه في الفترة اللي فاتت؟ لو سبت نفسك تحسه بجد، ولو ليوم واحد بس، هيحصل إيه؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 1;
UPDATE "JournalPrompt" SET "textAr" = 'اذكر ثلاث حاجات بسيطة من الأسبوع ده خلّتك تحس بالاستقرار أو الأمان.', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 2;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب جملة كنت هتقولها لصاحبك لو كان بيمر بنفس اللي إنت فيه. دلوقتي قولها لنفسك.', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 3;
UPDATE "JournalPrompt" SET "textAr" = 'فين في حياتك بتقول ''أيوه'' وإنت جوّاك قاصد ''لأ''؟ هيكلفك إيه إنك تقول ''لأ'' مرة واحدة الأسبوع ده؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 4;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الاعتقاد عن نفسك اللي كبرت عليه، حتى لو لسه بتلاقي نفسك بتكرره أحيانًا؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 5;
UPDATE "JournalPrompt" SET "textAr" = 'مين في حياتك بيخليك تحس إنك على طبيعتك أكتر حاجة؟ إيه فيهم، أو فيك إنت، اللي بيسمح بده؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 6;
UPDATE "JournalPrompt" SET "textAr" = 'فين بتحمل الضغط النفسي في جسمك؟ إيه اللي بيحاول يقولهولك؟', "categoryAr" = 'الضغط النفسي' WHERE "dayNumber" = 7;
UPDATE "JournalPrompt" SET "textAr" = 'إيه القصة اللي بتفضل تحكيها عن نفسك واللي ممكن متبقاش صحيحة دلوقتي؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 8;
UPDATE "JournalPrompt" SET "textAr" = 'وصف بالظبط مكانك دلوقتي — خمس حاجات بتشوفها، وإزاي جسمك حاسس على الكرسي ده.', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 9;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة عملها جسمك عشانك النهاردة ومشكرتوش عليها؟', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 10;
UPDATE "JournalPrompt" SET "textAr" = 'افتكر آخر مرة حسيت فيها إنك مش قادر تستوعب. إيه اللي كنت محتاجه في اللحظة دي ومحصلتش عليه؟', "categoryAr" = 'تنظيم المشاعر' WHERE "dayNumber" = 11;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي كنت هتجرب لو عارف إنك مش هتفشل — وإيه نسخة صغيرة منه ممكن تجربها الشهر ده؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 12;
UPDATE "JournalPrompt" SET "textAr" = 'مين اللي شكّل اللي إنت عليه دلوقتي بطريقة ماقلتلوش عنها؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 13;
UPDATE "JournalPrompt" SET "textAr" = 'إيه معنى ''تسيبها تطلع'' بالنسبالك النهاردة — إحساس، حقيقة، ولا توتر مستعد تسيبه؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 14;
UPDATE "JournalPrompt" SET "textAr" = 'فيه محادثة إنت باعد عنها؟ إنت خايف تغيّر إيه؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 15;
UPDATE "JournalPrompt" SET "textAr" = 'شكل إيه لما بتدي وقتك بسخاء بسبب الذنب مش رغبة حقيقية؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 16;
UPDATE "JournalPrompt" SET "textAr" = 'لاحظ نفسك لمدة دقيقة قبل ما تكتب. إيه اللي اتغيّر، حتى لو بسيط؟', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 17;
UPDATE "JournalPrompt" SET "textAr" = 'شكل إيه إنك تفشل في حاجة وتفضل تعامل نفسك بلطف؟', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 18;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة على كتافك دلوقتي مش أصلاً شغلتك إنك تحملها؟', "categoryAr" = 'الضغط النفسي' WHERE "dayNumber" = 19;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الخوف اللي بتاخد قرارات أصغر بسببه من غير ما تحس؟ إيه خطوة مناسبة تعدي بيها منه؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 20;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب ثلاث حاجات عن نفسك مالهاش علاقة بالإنتاجية أو الإنجاز.', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 21;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي محتاج منه أكتر من أقرب الناس ليك — وطلبته منهم بوضوح قبل كده؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 22;
UPDATE "JournalPrompt" SET "textAr" = 'إمتى بتحس إنك بتمثّل دور، وإمتى بتحس إنك حقيقي جدًا؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 23;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة صعبة مريت بيها وإنت دلوقتي، بطريقة غريبة، ممتن ليها؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 24;
UPDATE "JournalPrompt" SET "textAr" = 'إيه طريقتك المعتادة إنك تخدّر مشاعرك لما الأمور تبقى صعبة؟ ممكن تكون بتحميك من إيه؟', "categoryAr" = 'تنظيم المشاعر' WHERE "dayNumber" = 25;
UPDATE "JournalPrompt" SET "textAr" = 'فين بيروح دماغك لما مفيش حاجة موجّهاه؟ إيه اللي فاضل يرجعله؟', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 26;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حد حافظت عليه بنجاح مؤخرًا حتى لو كان غير مريح؟ حسيت إزاي بعد كده؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 27;
UPDATE "JournalPrompt" SET "textAr" = 'لو صوتك الناقد الداخلي هيعرّف نفسه بصدق، هيقول إيه — وصوت مين بيستعير؟', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 28;
UPDATE "JournalPrompt" SET "textAr" = 'شكل ''الكفاية'' إيه بالنسبالك النهاردة، بعيدًا عن اللي اتعلمت إنك تجري وراه؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 29;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب رسالة قصيرة لنفسك بعد سنة من دلوقتي. إيه اللي بتتمنى يكون هدّى؟ وإيه اللي بتتمنى يكون كبر؟', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 30;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي لسه ماسكه وخلاص وقته خلص؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 31;
UPDATE "JournalPrompt" SET "textAr" = 'لو ديت نفسك إذن كامل إنك تبطّل تحاول تتحكم في نتيجة معينة، هتعمل إيه مختلف النهاردة؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 32;
UPDATE "JournalPrompt" SET "textAr" = 'أي نسخة من نفسك بتحزن عليها، حتى لو بهدوء؟ يعني إيه إنك تسيبها تروح بلطف؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 33;
UPDATE "JournalPrompt" SET "textAr" = 'فيه اعتذار إنت مستني تسمعه وممكن محصلش أبدًا؟ محتاج إيه عشان تكمل من غيره؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 34;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة فاضل تقراها أو تشيكها أو تعيدها في دماغك — وبتدور على إيه؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 35;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب عن خطة أو هوية ماتحققتش. علّمتك إيه قبل ما تسيبها؟', "categoryAr" = 'التحرر من الماضي' WHERE "dayNumber" = 36;
UPDATE "JournalPrompt" SET "textAr" = 'افتكر فترة صعبة عديت منها. اتكلت على إيه ونسيت إنه كان موجود؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 37;
UPDATE "JournalPrompt" SET "textAr" = 'إيه علامة صغيرة الأسبوع ده إنك أحسن مما بتفتكر؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 38;
UPDATE "JournalPrompt" SET "textAr" = 'لما الأمور تحصل غلط، إيه القصة اللي بتحكيها عن نفسك؟ هل هي عادلة؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 39;
UPDATE "JournalPrompt" SET "textAr" = 'الصعوبة المتكررة علّمتك إيه ماكانش ممكن الارتياح يعلمهولك؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 40;
UPDATE "JournalPrompt" SET "textAr" = 'اذكر حد شافك بتصارع وفضل مؤمن بيك. بيشوف فيك إيه إنت أحيانًا مش قادر تشوفه؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 41;
UPDATE "JournalPrompt" SET "textAr" = 'شكل إيه إنك تدي نفسك حقها بس عشان لسه موجود؟', "categoryAr" = 'المرونة النفسية' WHERE "dayNumber" = 42;
UPDATE "JournalPrompt" SET "textAr" = 'إيه قيمة إنت متمسك بيها بس نادرًا ما بتتكلم عنها؟ فين بتظهر في حياتك؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 43;
UPDATE "JournalPrompt" SET "textAr" = 'إنت عايش بتعريف مين للنجاح — بتاعك ولا بتاع حد تاني؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 44;
UPDATE "JournalPrompt" SET "textAr" = 'إيه جزء من شخصيتك صغّرته عشان تبقى محبوب أكتر، وبتفتقده؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 45;
UPDATE "JournalPrompt" SET "textAr" = 'لو محدش بيتفرج عليك أو بيقيّمك، هتقضي وقت أكتر بتعمل إيه؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 46;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة كنت مصدقها عن نفسك وعمرك 15 سنة ولسه بتتحكم فيك من غير ما تحس؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 47;
UPDATE "JournalPrompt" SET "textAr" = 'فين في حياتك بتمثّل ثقة إنت مش حاسس بيها فعلًا؟', "categoryAr" = 'القيم والهوية' WHERE "dayNumber" = 48;
UPDATE "JournalPrompt" SET "textAr" = 'فيه حد ماسامحتوش — حتى نفسك؟ المسامحة بتحميك من إيه، أو بتكلفك إيه؟', "categoryAr" = 'المسامحة' WHERE "dayNumber" = 49;
UPDATE "JournalPrompt" SET "textAr" = 'إيه غلطة فاضل تعاقب نفسك عليها بعد ما اتعلمت درسها من زمان؟', "categoryAr" = 'المسامحة' WHERE "dayNumber" = 50;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب عن مرة حد جرحك وبعدين فهمت ليه. ده غيّر حاجة؟', "categoryAr" = 'المسامحة' WHERE "dayNumber" = 51;
UPDATE "JournalPrompt" SET "textAr" = 'هتحس إزاي لو سامحت نفسك على حاجة مقلتهاش لحد؟', "categoryAr" = 'المسامحة' WHERE "dayNumber" = 52;
UPDATE "JournalPrompt" SET "textAr" = 'مين محتاج ترحمه النهاردة، حتى لو مش مستاهل ده في نظرك؟', "categoryAr" = 'المسامحة' WHERE "dayNumber" = 53;
UPDATE "JournalPrompt" SET "textAr" = 'الراحة الحقيقية حاسسها إزاي — مش سكرول، مش نوم من التعب، لكن راحة فعلية؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 54;
UPDATE "JournalPrompt" SET "textAr" = 'إمتى آخر مرة عملت حاجة من غير أي هدف مربوط بيها؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 55;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الإشارات اللي جسمك بيديهالك قبل الاحتراق الوظيفي؟ إنت بتسمعها؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 56;
UPDATE "JournalPrompt" SET "textAr" = 'لو ديت نفسك ساعة من غير استعجال بكرة، هتحب تعمل بيها إيه فعلًا؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 57;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة فاضل ''تكمل فيها بالقوة'' وهي فعلًا محتاجاك توقف؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 58;
UPDATE "JournalPrompt" SET "textAr" = 'اكتب عن مكان، حقيقي أو خيالي، بتحس فيه بارتياح كامل. إيه اللي بيخليه كده؟', "categoryAr" = 'الراحة والاستشفاء' WHERE "dayNumber" = 59;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة نفسك حد يسألك عنها بشكل مباشر؟', "categoryAr" = 'التواصل' WHERE "dayNumber" = 60;
UPDATE "JournalPrompt" SET "textAr" = 'لما بتزعل، بتميل تسكت ولا تعلّي صوتك؟ محتاج إيه فعلًا في اللحظة دي؟', "categoryAr" = 'التواصل' WHERE "dayNumber" = 61;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حقيقة هدّيتها لما بتحكيها لحد ما بقت مش مسموعة خالص؟', "categoryAr" = 'التواصل' WHERE "dayNumber" = 62;
UPDATE "JournalPrompt" SET "textAr" = 'افتكر آخر خلاف حصلك. كنت عايز الطرف التاني يفهم إيه عنك؟', "categoryAr" = 'التواصل' WHERE "dayNumber" = 63;
UPDATE "JournalPrompt" SET "textAr" = 'مين أصعب واحد تكون صادق معاه — وبتحمي إيه لما تفضل ساكت؟', "categoryAr" = 'التواصل' WHERE "dayNumber" = 64;
UPDATE "JournalPrompt" SET "textAr" = 'إيه قرار بتأجله عشان خايف تكون غلطان؟', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 65;
UPDATE "JournalPrompt" SET "textAr" = 'هتعمل إيه لو وثقت في نفسك تمامًا، ليوم واحد بس؟', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 66;
UPDATE "JournalPrompt" SET "textAr" = 'اذكر خوف هو في الحقيقة مجرد إزعاج لابس زي أكبر منه.', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 67;
UPDATE "JournalPrompt" SET "textAr" = 'إيه أصغر حاجة شجاعة ممكن تعملها النهاردة، وإنت باعد عنها؟', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 68;
UPDATE "JournalPrompt" SET "textAr" = 'إيه كان بيخوّفك زمان ودلوقتي مبقاش بيخوّفك؟ إيه اللي اتغيّر؟', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 69;
UPDATE "JournalPrompt" SET "textAr" = 'لو الفشل كان مجرد معلومة مش حكم على قيمتك، هتجرب إيه؟', "categoryAr" = 'الخوف والشجاعة' WHERE "dayNumber" = 70;
UPDATE "JournalPrompt" SET "textAr" = 'إمتى آخر مرة ضحكت جامد لدرجة إنك نسيت إيه كان مقلقك؟', "categoryAr" = 'الفرح واللعب' WHERE "dayNumber" = 71;
UPDATE "JournalPrompt" SET "textAr" = 'إيه كنت بتحب تعمله وإنت صغير وبطّلت من غير ما تحس تخصصله وقت؟', "categoryAr" = 'الفرح واللعب' WHERE "dayNumber" = 72;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة صغيرة وشوية سخيفة بس دايمًا بتفرحك؟', "categoryAr" = 'الفرح واللعب' WHERE "dayNumber" = 73;
UPDATE "JournalPrompt" SET "textAr" = 'وصف لحظة الشهر ده حسيت فيها إنك على طبيعتك تمامًا من غير ما تفكر في نفسك.', "categoryAr" = 'الفرح واللعب' WHERE "dayNumber" = 74;
UPDATE "JournalPrompt" SET "textAr" = 'لو الفرح كان تمرين مش مجرد إحساس بيحصلك، هتتمرن على إيه الأسبوع ده؟', "categoryAr" = 'الفرح واللعب' WHERE "dayNumber" = 75;
UPDATE "JournalPrompt" SET "textAr" = 'إيه فصل من حياتك حاسس إنه بيقفل بهدوء؟ عايز تقفله كويس إزاي؟', "categoryAr" = 'الختام والبدايات' WHERE "dayNumber" = 76;
UPDATE "JournalPrompt" SET "textAr" = 'هتحب تقول إيه للشخص اللي كنته من سنة، دلوقتي؟', "categoryAr" = 'الختام والبدايات' WHERE "dayNumber" = 77;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة مستعد تبدأها، حتى لو مش هتبدأها بشكل مثالي؟', "categoryAr" = 'الختام والبدايات' WHERE "dayNumber" = 78;
UPDATE "JournalPrompt" SET "textAr" = 'لو النهاردة أول يوم في فصل جديد من حياتك، هتحب يكون عن إيه؟', "categoryAr" = 'الختام والبدايات' WHERE "dayNumber" = 79;
UPDATE "JournalPrompt" SET "textAr" = 'إيه نهاية بتتجنبها لأنها حاسس إنها نهائية، مع إنك عارف إن وقتها جه؟', "categoryAr" = 'الختام والبدايات' WHERE "dayNumber" = 80;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي بيخليك تنسى الوقت بطريقة كويسة؟', "categoryAr" = 'الهدف' WHERE "dayNumber" = 81;
UPDATE "JournalPrompt" SET "textAr" = 'إمتى بتحس إنك مفيد أكتر حاجة — مش مشغول، لكن مفيد فعلًا؟', "categoryAr" = 'الهدف' WHERE "dayNumber" = 82;
UPDATE "JournalPrompt" SET "textAr" = 'هتحب الناس تقول إيه عن إحساسهم معاك، مش عن اللي حققته؟', "categoryAr" = 'الهدف' WHERE "dayNumber" = 83;
UPDATE "JournalPrompt" SET "textAr" = 'إيه طريقة بسيطة ممكن تعيش بيها أقرب لقيمك الأسبوع ده؟', "categoryAr" = 'الهدف' WHERE "dayNumber" = 84;
UPDATE "JournalPrompt" SET "textAr" = 'لو حياتك اليومية لازم تعكس أهم حاجة بالنسبالك، إيه أول حاجة هتتغير؟', "categoryAr" = 'الهدف' WHERE "dayNumber" = 85;
UPDATE "JournalPrompt" SET "textAr" = 'إيه نمط في علاقاتك بيفضل يظهر بأشكال مختلفة؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 86;
UPDATE "JournalPrompt" SET "textAr" = 'إمتى بتحس إنك على طبيعتك أكتر، وإيه اللي بيبعدك عن ده غالبًا؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 87;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة بتعملها من غير ما تفكر ممكن تستاهل تلاحظها فعلًا؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 88;
UPDATE "JournalPrompt" SET "textAr" = 'إيه مجاملة بتلاقي صعوبة تقبلها؟ ليه في رأيك؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 89;
UPDATE "JournalPrompt" SET "textAr" = 'لو مزاجك دلوقتي كان نشرة جوية، هيقول إيه — وإيه اللي جاي؟', "categoryAr" = 'الوعي الذاتي' WHERE "dayNumber" = 90;
UPDATE "JournalPrompt" SET "textAr" = 'إيه محادثة صعبة خلتك تقرب من حد أكتر؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 91;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة عملتها إنت زمان ونفسك دلوقتي ممتن ليها؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 92;
UPDATE "JournalPrompt" SET "textAr" = 'مين وقف جنبك مؤخرًا بطريقة مشكرتهوش عليها كويس؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 93;
UPDATE "JournalPrompt" SET "textAr" = 'إيه جزء من روتينك اليومي هتفتقده لو اختفى؟', "categoryAr" = 'الامتنان' WHERE "dayNumber" = 94;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي محتاج تسمعه النهاردة ولسه محدش قالهولك؟', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 95;
UPDATE "JournalPrompt" SET "textAr" = 'بتعامل نفسك إزاي عادةً بعد أي غلطة؟ كنت هتعامل صاحبك كده؟', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 96;
UPDATE "JournalPrompt" SET "textAr" = 'إيه توقع عن نفسك ممكن يكون فعلًا مش واقعي؟', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 97;
UPDATE "JournalPrompt" SET "textAr" = 'اذكر طريقة كنت قاسي فيها على نفسك النهاردة، وقدّم لنفسك نسخة ألطف من الفكرة دي.', "categoryAr" = 'الرأفة الذاتية' WHERE "dayNumber" = 98;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حد عارف إنك محتاج تحطه بس فاضل بتأجله؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 99;
UPDATE "JournalPrompt" SET "textAr" = 'مين في حياتك بيخلي قول ''لأ'' أصعب حاجة — وليه في رأيك؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 100;
UPDATE "JournalPrompt" SET "textAr" = 'بيكلفك إيه لما مش بتحمي وقتك أو طاقتك؟', "categoryAr" = 'الحدود الشخصية' WHERE "dayNumber" = 101;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة فاهمها دلوقتي ماكانش ممكن تفهمها من كام سنة؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 102;
UPDATE "JournalPrompt" SET "textAr" = 'إيه إزعاج بتتجنبه دلوقتي ممكن يكون في الحقيقة نمو لابس شكل تاني؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 103;
UPDATE "JournalPrompt" SET "textAr" = 'لو بصيت على اليوم ده بالظبط بعد خمس سنين، هتتمنى تكون عملت فيه إيه؟', "categoryAr" = 'النمو الشخصي' WHERE "dayNumber" = 104;
UPDATE "JournalPrompt" SET "textAr" = 'هتحب الناس القريبة منك تفهم إيه عن طريقتك في التعبير عن الحب؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 105;
UPDATE "JournalPrompt" SET "textAr" = 'فيه علاقة في حياتك بتاخد منك أكتر مما بتديك دلوقتي؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 106;
UPDATE "JournalPrompt" SET "textAr" = 'إيه فعل بسيط من التواصل ممكن تقدمه لحد النهاردة؟', "categoryAr" = 'العلاقات' WHERE "dayNumber" = 107;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الفرق بين الحاجات اللي بتضغط عليك واللي تقدر تتصرف فيها، والحاجات اللي بس تقدر تتقبلها؟', "categoryAr" = 'الضغط النفسي' WHERE "dayNumber" = 108;
UPDATE "JournalPrompt" SET "textAr" = 'لو ضغطك النفسي يقدر يتكلم، هيحاول يحذرك من إيه؟', "categoryAr" = 'الضغط النفسي' WHERE "dayNumber" = 109;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة ممكن تشيلها من على كتافك الأسبوع ده من غير ما حاجة تتهد؟', "categoryAr" = 'الضغط النفسي' WHERE "dayNumber" = 110;
UPDATE "JournalPrompt" SET "textAr" = 'إيه أصوات بتسمعها دلوقتي ماكنتش واخد بالك منها من شوية؟', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 111;
UPDATE "JournalPrompt" SET "textAr" = 'فين في جسمك بتحس بأكتر توتر دلوقتي؟ اتنفس فيه لحظة قبل ما تكتب.', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 112;
UPDATE "JournalPrompt" SET "textAr" = 'اللحظة الحالية حاسسها إزاي فعلًا، من غير ما تحكم عليها إنها كويسة أو وحشة؟', "categoryAr" = 'اليقظة الذهنية' WHERE "dayNumber" = 113;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الإحساس اللي بيزورك أكتر من غير ما تستناه؟ بيحاول يخليك تعمل إيه عادةً؟', "categoryAr" = 'تنظيم المشاعر' WHERE "dayNumber" = 114;
UPDATE "JournalPrompt" SET "textAr" = 'إيه اللي بيساعدك ترجع لنفسك بعد لحظة صعبة؟', "categoryAr" = 'تنظيم المشاعر' WHERE "dayNumber" = 115;
UPDATE "JournalPrompt" SET "textAr" = 'إيه الفرق بين إحساسك الحقيقي دلوقتي وإزاي بتبان قدام الناس النهاردة؟', "categoryAr" = 'تنظيم المشاعر' WHERE "dayNumber" = 116;
UPDATE "JournalPrompt" SET "textAr" = 'إيه حاجة في شخصيتك خدت منك سنين عشان تقدرها؟', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 117;
UPDATE "JournalPrompt" SET "textAr" = 'بتحتفل بإنجازاتك إزاي عادةً — وبتسمح لنفسك بده في الإنجاز ده؟', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 118;
UPDATE "JournalPrompt" SET "textAr" = 'هتعمل إيه النهاردة لو مصدق تمامًا إنك تستاهل الراحة؟', "categoryAr" = 'حب الذات' WHERE "dayNumber" = 119;
